language: node_js
node_js:
- '6'
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
  - node_modules
branches:
  only:
  - master
before_install:
- npm i -g yarn --cache-min 999999999
install:
- yarn
script:
- make build
deploy:
  provider: gcs
  access_key_id: GOOG6FMDULPSTOOJ4XZH
  secret_access_key:
    secure: nySg105ZzdvglzLqHVksJDjjhQkklZ9G+eLSohAuXQPaVKOtepTMA3EKL/ZyEYHCITU/vTUdeYQWPCKEaYikA2StXgLfW0QMsY+tu2yrbc3fqb/fVe3hESpxk3WoWnBfHJpI9yIPoVCFxGZZ+94BkHSgyRDn1nhaY0CLrEt0RmhQd3g40xZ1l19Ek7h8uuqnqL9v1hKd9uXK1B9MoGQ/0/pFbVB12JU6fH5oAX23RI2J8qQHMQPj2x9Y3ZcwZNzde7EQ/Nf1G6kPdeTLFv3DE3RfhnMPtmSAr79wXEAvyamPdqaWmTBTkXmLXI9pyM3C0Xm1X8G87zsyOv/KqGkznelz0k3AaNkdxNkdLEcHgvrjEJUR93+yuOt1bJZzT2EfLxc0P/0iIjxOA9/CgtBpz69S75nNZAOUbZkDLq38IfGO55149WAj2yxtVSfaTBCT8X/ylVdW9DQwr1Za0zM+XmzjXCqvrceiEEJNPB3Fjh0L5HZkJgFDYnzV3/G3FPeVfoZ6Mr20y7Q7d0cVD511nr+csbbFadsBDGRPHutCZ83XunIa1QbQHMZYWBlzvY4bXnkG4jaHpsWGaLGZEXApcpuLfxlpX6K8pFc2BbpKH7AMClqxRQQpNFFKE74+2KilaTMdSJb3AbwVLpxN8tZjW4s6KiIcRKgbZNVTnFjr2fI=
  bucket: dagbjartur.me
  local-dir: dist
  skip_cleanup: true
  acl: public-read
  cache_control: "no-cache"
  on:
    repo: dagbjartur/dagbjartur
